CXXFLAGS=$CXXFLAGS -DQUDA_PRECISION=14 -DQUDA_RECONSTRUCT=7
CXXFLAGS=$CXXFLAGS -DBUILD_QDP_INTERFACE
CXXFLAGS=$CXXFLAGS -DBUILD_MILC_INTERFACE
CXXFLAGS=$CXXFLAGS -DGPU_WILSON_DIRAC
CXXFLAGS=$CXXFLAGS -DGPU_CLOVER_DIRAC -DGPU_WILSON_DIRAC -DGPU_GAUGE_TOOLS
CXXFLAGS=$CXXFLAGS -DQUDA_FAST_COMPILE_REDUCE
CXXFLAGS=$CXXFLAGS -DQUDA_FAST_COMPILE_DSLASH
CXXFLAGS=$CXXFLAGS -DGPU_MULTIGRID
