CXXFLAGS=$CXXFLAGS -DQUDA_PRECISION=14 -DQUDA_RECONSTRUCT=7
CXXFLAGS=$CXXFLAGS -DBUILD_QDP_INTERFACE
CXXFLAGS=$CXXFLAGS -DBUILD_MILC_INTERFACE
CXXFLAGS=$CXXFLAGS -DGPU_GAUGE_ALG -DGPU_GAUGE_TOOLS -DGPU_UNITARIZE
CXXFLAGS=$CXXFLAGS -DGPU_WILSON_DIRAC
CXXFLAGS=$CXXFLAGS -DGPU_DOMAIN_WALL_DIRAC
CXXFLAGS=$CXXFLAGS -DGPU_STAGGERED_DIRAC -DGPU_UNITARIZE -DGPU_FATLINK
CXXFLAGS=$CXXFLAGS -DGPU_CLOVER_DIRAC -DGPU_WILSON_DIRAC -DGPU_GAUGE_TOOLS
# CXXFLAGS=$CXXFLAGS -DGPU_TWISTED_MASS_DIRAC -DGPU_WILSON_DIRAC
# CXXFLAGS=$CXXFLAGS -DGPU_TWISTED_CLOVER_DIRAC -DGPU_CLOVER_DIRAC -DGPU_TWISTED_MASS_DIRAC -DGPU_WILSON_DIRAC -DGPU_GAUGE_TOOLS
# CXXFLAGS=$CXXFLAGS -DGPU_CLOVER_HASENBUSCH_TWIST -DGPU_TWISTED_CLOVER_DIRAC -DGPU_CLOVER_DIRAC -DGPU_WILSON_DIRAC -DGPU_GAUGE_TOOLS
# CXXFLAGS=$CXXFLAGS -DGPU_NDEG_TWISTED_MASS_DIRAC
CXXFLAGS=$CXXFLAGS -DGPU_MULTIGRID
