TARG=`{echo $TARG | sed 's,dslash,staggered_dslash,g;s,invert,staggered_invert,g'}

CXXFLAGS=$CXXFLAGS -DQUDA_PRECISION=14 -DQUDA_RECONSTRUCT=7
CXXFLAGS=$CXXFLAGS -DQUDA_FAST_COMPILE_REDUCE
CXXFLAGS=$CXXFLAGS -DQUDA_FAST_COMPILE_DSLASH
CXXFLAGS=$CXXFLAGS -DBUILD_QDP_INTERFACE
CXXFLAGS=$CXXFLAGS -DBUILD_MILC_INTERFACE
CXXFLAGS=$CXXFLAGS -DGPU_STAGGERED_DIRAC -DGPU_UNITARIZE -DGPU_FATLINK
# CXXFLAGS=$CXXFLAGS -DGPU_MULTIGRID
