CXXFLAGS=$CXXFLAGS -DQUDA_PRECISION=8 -DQUDA_RECONSTRUCT=4
CXXFLAGS=$CXXFLAGS -DQUDA_FAST_COMPILE_REDUCE
CXXFLAGS=$CXXFLAGS -DQUDA_FAST_COMPILE_DSLASH
CXXFLAGS=$CXXFLAGS -DBUILD_QDP_INTERFACE
CXXFLAGS=$CXXFLAGS -DBUILD_MILC_INTERFACE
CXXFLAGS=$CXXFLAGS -DGPU_WILSON_DIRAC

<conf.single.mk
